---
title: "Week 9 Code along & Challenge"
author: "Lew Bo Cong"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## 1. Code Along

### I. Tidy data

#### Slide #8
```{r, eval=TRUE,echo=TRUE}
library(tidyverse)

tidydata <- tribble(
  ~country, ~year, ~cases, ~population,
  "Afghanistan", 1999, 745, 19987071,
  "Afghanistan", 2000, 2666, 20595360,
  "Brazil", 1999, 37737, 172006362,
  "Brazil", 2000, 80488, 174504898,
  "China", 1999, 212258, 1272915272,
  "China", 2000, 213766, 1280428583)

tidydata

nontidydata <- tribble(
  ~country,~year,~rate,
  "Afghanistan", 1999, "745/19987071",
  "Afghanistan", 2000, "2666/20595360",
  "Brazil", 1999, "37737/172006362",
  "Brazil", 2000, "80488/174504898",
  "China", 1999, "212258/1272915272",
  "China", 2000, "213766/1280428583")

nontidydata
```

#### Slide 9
```{r, eval=TRUE,echo=TRUE}
tidydata %>%
  group_by(year) %>%
  summarize(total_cases = sum(cases))
```

### II. Tidy-ing data

#### Slide 11
```{r, eval=TRUE,echo=TRUE}
nontidydata

tidieddata <- nontidydata %>%
  separate(rate, into = c("cases",
                          "population"),
                            sep = "/")

tidieddata
```

#### Slide 12
```{r, eval=TRUE,echo=TRUE}
newtidieddata <- tidieddata %>%
  pivot_longer(
    cols = cases:population,
    names_to = "measurement",
    values_to = "value"
  )

newtidieddata
```

#### Slide 13
```{r, eval=TRUE,echo=TRUE}
ggplot(newtidieddata) +
  aes(x = year, y = value, colour = country) +
  geom_point() + 
  geom_line(aes(group = country)) + 
  facet_wrap(~measurement) + 
  theme_bw()
```

#### Slide 14
```{r, eval=TRUE,echo=TRUE}
df <- tribble(
  ~id, ~bp1, ~bp2,
  "A",100,120,
  "B",140,115,
  "C",120,125
)

df

df %>%
  pivot_longer(
    cols = bp1:bp2,
    names_to = "measurement",
    values_to = "value"
)
```

#### Slide 18
```{r, eval=TRUE,echo=TRUE}
newtidieddata

newtidieddata %>%
  pivot_wider(names_from = "measurement",
              values_from = "value")
```

#### Slide 19
```{r, eval=TRUE,echo=TRUE}
df <- tribble(
  ~id, ~measurement, ~value,
  "A","bp1",100,
  "B","bp1",140,
  "B","bp2",115,
  "A","bp2",120,
  "A","bp3",105
)

df

df %>% 
  pivot_wider(
    names_from = measurement,
    values_from = value
  )

```

### III. Scraping data

#### Slide 22
```{r, eval=TRUE,echo=TRUE}
library(rvest)
webpage <- read_html("https://books.toscrape.com")
table <- html_elements(webpage, "body")
```

### IV. Access & Collect data using APIs in R

#### Slide 25
```{r, eval=FALSE,echo=TRUE}
library(c(httr, jsonlite))

# current data
current_county_data_url <-
"https://api.covidactnow.org/v2/counties.csv?apiKey=YOUR_KEY_HERE"
raw_data <- GET(current_county_data_url)
raw_data$status
raw_data$content

# historic data
historic_county_data_url <-
"https://api.covidactnow.org/v2/counties.timeseries.csv?apiKey=YOUR_KEY_HERE"
raw_data <- GET(historic_county_data_url)
raw_data$status
raw_data$content

# individual location data
individual_loc_data_url <-
"https://api.covidactnow.org/v2/county/{state}.csv?apiKey=YOUR_KEY_HERE"
raw_data <- GET(individual_loc_data_url)
raw_data$status
raw_data$content

```

## 2. Challenge

### Part 1
```{r, eval=TRUE,echo=TRUE}
library(tidyverse)

tidiedbill <- billboard %>%
  pivot_longer(
    cols = starts_with("wk"),
    names_to = "week",
    values_to = "rank",
    values_drop_na = TRUE
  ) %>% mutate(week = parse_number(week))

ggplot(tidiedbill) +
  aes(x = week, y = rank) +
  geom_line()
```

### Part 2
```{r, eval=TRUE,echo=TRUE}

tidiedcms <- cms_patient_experience %>%
  pivot_wider(
    id_cols = starts_with("org"),
    names_from = measure_cd,
    values_from = prf_rate
  )

tidiedcms
```